import type { INodeProperties } from 'n8n-workflow';
import { billingAddressField, currencyOptions, customerLocator, metadataField } from '../../shared/descriptions';

const show = { resource: ['checkout'], operation: ['create'] };

export const checkoutCreateDescription: INodeProperties[] = [
	{
		displayName: 'Product Names or IDs',
		name: 'products',
		type: 'multiOptions',
		typeOptions: { loadOptionsMethod: 'getProductOptions' },
		default: [],
		required: true,
		displayOptions: { show },
		description: 'Products available to select at this checkout. The first one is preselected. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
		routing: { send: { type: 'body', property: 'products' } },
	},
	{
		...customerLocator(show, false),
		description: 'Attach the checkout to an existing customer (optional)',
		routing: { send: { type: 'body', property: 'customer_id', value: '={{$value.value || undefined}}' } },
	},
	metadataField('metadata', 'metadata', 'Metadata', show),
	metadataField('customerMetadata', 'customer_metadata', 'Customer Metadata', show),
	billingAddressField('customerBillingAddress', 'customer_billing_address', show),
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show },
		options: [
			{
				displayName: 'Allow Discount Codes',
				name: 'allow_discount_codes',
				type: 'boolean',
				default: true,
				routing: { request: { body: { allow_discount_codes: '={{$value}}' } } },
			},
			{
				displayName: 'Allow Trial',
				name: 'allow_trial',
				type: 'boolean',
				default: true,
				description: 'Whether to honor a trial configured on the product. If false, the trial is disabled for this checkout.',
				routing: { request: { body: { allow_trial: '={{$value}}' } } },
			},
			{
				displayName: 'Amount (Cents)',
				name: 'amount',
				type: 'number',
				default: 0,
				description: "Amount in cents before discounts/taxes. Only used for custom (pay-what-you-want) prices.",
				routing: { request: { body: { amount: '={{$value}}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'options',
				options: currencyOptions,
				default: 'usd',
				routing: { request: { body: { currency: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Billing Name',
				name: 'customer_billing_name',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_billing_name: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Email',
				name: 'customer_email',
				type: 'string',
				placeholder: 'name@email.com',
				default: '',
				routing: { request: { body: { customer_email: '={{$value}}' } } },
			},
			{
				displayName: 'Customer IP Address',
				name: 'customer_ip_address',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_ip_address: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Name',
				name: 'customer_name',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_name: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Tax ID',
				name: 'customer_tax_id',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_tax_id: '={{$value}}' } } },
			},
			{
				displayName: 'Discount ID',
				name: 'discount_id',
				type: 'string',
				default: '',
				routing: { request: { body: { discount_id: '={{$value}}' } } },
			},
			{
				displayName: 'Embed Origin',
				name: 'embed_origin',
				type: 'string',
				default: '',
				routing: { request: { body: { embed_origin: '={{$value}}' } } },
			},
			{
				displayName: 'External Customer ID',
				name: 'external_customer_id',
				type: 'string',
				default: '',
				routing: { request: { body: { external_customer_id: '={{$value}}' } } },
			},
			{
				displayName: 'Is Business Customer',
				name: 'is_business_customer',
				type: 'boolean',
				default: false,
				routing: { request: { body: { is_business_customer: '={{$value}}' } } },
			},
			{
				displayName: 'Locale',
				name: 'locale',
				type: 'string',
				placeholder: 'e.g. en, en-US, fr-FR',
				default: '',
				routing: { request: { body: { locale: '={{$value}}' } } },
			},
			{
				displayName: 'Max Seats',
				name: 'max_seats',
				type: 'number',
				default: 1,
				routing: { request: { body: { max_seats: '={{$value}}' } } },
			},
			{
				displayName: 'Min Seats',
				name: 'min_seats',
				type: 'number',
				default: 1,
				routing: { request: { body: { min_seats: '={{$value}}' } } },
			},
			{
				displayName: 'Require Billing Address',
				name: 'require_billing_address',
				type: 'boolean',
				default: false,
				description: 'Whether to require the full billing address instead of just the country',
				routing: { request: { body: { require_billing_address: '={{$value}}' } } },
			},
			{
				displayName: 'Return URL',
				name: 'return_url',
				type: 'string',
				default: '',
				routing: { request: { body: { return_url: '={{$value}}' } } },
			},
			{
				displayName: 'Seats',
				name: 'seats',
				type: 'number',
				default: 1,
				routing: { request: { body: { seats: '={{$value}}' } } },
			},
			{
				displayName: 'Subscription ID',
				name: 'subscription_id',
				type: 'string',
				default: '',
				description: 'Upgrade this existing subscription instead of creating a new one',
				routing: { request: { body: { subscription_id: '={{$value}}' } } },
			},
			{
				displayName: 'Success URL',
				name: 'success_url',
				type: 'string',
				default: '',
				routing: { request: { body: { success_url: '={{$value}}' } } },
			},
			{
				displayName: 'Trial Interval',
				name: 'trial_interval',
				type: 'options',
				options: [
					{ name: 'Day', value: 'day' },
					{ name: 'Week', value: 'week' },
					{ name: 'Month', value: 'month' },
					{ name: 'Year', value: 'year' },
				],
				default: 'month',
				routing: { request: { body: { trial_interval: '={{$value}}' } } },
			},
			{
				displayName: 'Trial Interval Count',
				name: 'trial_interval_count',
				type: 'number',
				default: 1,
				routing: { request: { body: { trial_interval_count: '={{$value}}' } } },
			},
		],
	},
];
