import type { INodeProperties } from 'n8n-workflow';
import { billingAddressField, currencyOptions, metadataField } from '../../shared/descriptions';

const show = { resource: ['checkout'], operation: ['update'] };

export const checkoutUpdateDescription: INodeProperties[] = [
	{
		displayName: 'Checkout ID',
		name: 'checkoutId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show },
		description: 'The ID of the checkout session to update',
	},
	metadataField('metadata', 'metadata', 'Metadata', show),
	metadataField('customerMetadata', 'customer_metadata', 'Customer Metadata', show),
	billingAddressField('customerBillingAddress', 'customer_billing_address', show),
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show },
		options: [
			{
				displayName: 'Allow Discount Codes',
				name: 'allow_discount_codes',
				type: 'boolean',
				default: true,
				routing: { request: { body: { allow_discount_codes: '={{$value}}' } } },
			},
			{
				displayName: 'Allow Trial',
				name: 'allow_trial',
				type: 'boolean',
				default: true,
				routing: { request: { body: { allow_trial: '={{$value}}' } } },
			},
			{
				displayName: 'Amount (Cents)',
				name: 'amount',
				type: 'number',
				default: 0,
				routing: { request: { body: { amount: '={{$value}}' } } },
			},
			{
				displayName: 'Currency',
				name: 'currency',
				type: 'options',
				options: currencyOptions,
				default: 'usd',
				routing: { request: { body: { currency: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Billing Name',
				name: 'customer_billing_name',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_billing_name: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Email',
				name: 'customer_email',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_email: '={{$value}}' } } },
			},
			{
				displayName: 'Customer IP Address',
				name: 'customer_ip_address',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_ip_address: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Name',
				name: 'customer_name',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_name: '={{$value}}' } } },
			},
			{
				displayName: 'Customer Tax ID',
				name: 'customer_tax_id',
				type: 'string',
				default: '',
				routing: { request: { body: { customer_tax_id: '={{$value}}' } } },
			},
			{
				displayName: 'Discount ID',
				name: 'discount_id',
				type: 'string',
				default: '',
				routing: { request: { body: { discount_id: '={{$value}}' } } },
			},
			{
				displayName: 'Embed Origin',
				name: 'embed_origin',
				type: 'string',
				default: '',
				routing: { request: { body: { embed_origin: '={{$value}}' } } },
			},
			{
				displayName: 'Is Business Customer',
				name: 'is_business_customer',
				type: 'boolean',
				default: false,
				routing: { request: { body: { is_business_customer: '={{$value}}' } } },
			},
			{
				displayName: 'Locale',
				name: 'locale',
				type: 'string',
				default: '',
				routing: { request: { body: { locale: '={{$value}}' } } },
			},
			{
				displayName: 'Product ID',
				name: 'product_id',
				type: 'string',
				default: '',
				description: 'Switch the checkout to a different product',
				routing: { request: { body: { product_id: '={{$value}}' } } },
			},
			{
				displayName: 'Product Price ID',
				name: 'product_price_id',
				type: 'string',
				default: '',
				routing: { request: { body: { product_price_id: '={{$value}}' } } },
			},
			{
				displayName: 'Require Billing Address',
				name: 'require_billing_address',
				type: 'boolean',
				default: false,
				routing: { request: { body: { require_billing_address: '={{$value}}' } } },
			},
			{
				displayName: 'Return URL',
				name: 'return_url',
				type: 'string',
				default: '',
				routing: { request: { body: { return_url: '={{$value}}' } } },
			},
			{
				displayName: 'Seats',
				name: 'seats',
				type: 'number',
				default: 1,
				routing: { request: { body: { seats: '={{$value}}' } } },
			},
			{
				displayName: 'Success URL',
				name: 'success_url',
				type: 'string',
				default: '',
				routing: { request: { body: { success_url: '={{$value}}' } } },
			},
			{
				displayName: 'Trial Interval',
				name: 'trial_interval',
				type: 'options',
				options: [
					{ name: 'Day', value: 'day' },
					{ name: 'Week', value: 'week' },
					{ name: 'Month', value: 'month' },
					{ name: 'Year', value: 'year' },
				],
				default: 'month',
				routing: { request: { body: { trial_interval: '={{$value}}' } } },
			},
			{
				displayName: 'Trial Interval Count',
				name: 'trial_interval_count',
				type: 'number',
				default: 1,
				routing: { request: { body: { trial_interval_count: '={{$value}}' } } },
			},
		],
	},
];
