import type { INodeProperties } from 'n8n-workflow';

const show = { resource: ['subscription'], operation: ['export'] };

export const subscriptionExportDescription: INodeProperties[] = [
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show },
		options: [
			{
				displayName: 'Cancel at Period End',
				name: 'cancel_at_period_end',
				type: 'boolean',
				default: true,
				description: 'Whether to only include subscriptions set (or not set) to cancel at period end',
				routing: { request: { qs: { cancel_at_period_end: '={{$value}}' } } },
			},
			{
				displayName: 'Columns',
				name: 'columns',
				type: 'multiOptions',
				options: [
					{ name: 'Amount', value: 'amount' },
					{ name: 'Billing Country', value: 'billing_country' },
					{ name: 'Billing Name', value: 'billing_name' },
					{ name: 'Cancel at Period End', value: 'cancel_at_period_end' },
					{ name: 'Canceled At', value: 'canceled_at' },
					{ name: 'Cancellation Reason', value: 'cancellation_reason' },
					{ name: 'Currency', value: 'currency' },
					{ name: 'Current Period End', value: 'current_period_end' },
					{ name: 'Current Period Start', value: 'current_period_start' },
					{ name: 'Customer Name', value: 'customer_name' },
					{ name: 'Discount', value: 'discount' },
					{ name: 'Email', value: 'email' },
					{ name: 'Ended At', value: 'ended_at' },
					{ name: 'Ends At', value: 'ends_at' },
					{ name: 'Net Amount', value: 'net_amount' },
					{ name: 'Product', value: 'product' },
					{ name: 'Recurring Interval', value: 'recurring_interval' },
					{ name: 'Seats', value: 'seats' },
					{ name: 'Started At', value: 'started_at' },
					{ name: 'Status', value: 'status' },
					{ name: 'Trial End', value: 'trial_end' },
					{ name: 'Trial Start', value: 'trial_start' },
				],
				default: [],
				description: "Columns to include, in the order Polar returns them. Leave empty for Polar's default set.",
				routing: { request: { qs: { columns: '={{$value}}' } } },
			},
			{
				displayName: 'Product ID',
				name: 'product_id',
				type: 'string',
				default: '',
				routing: { request: { qs: { product_id: '={{$value}}' } } },
			},
			{
				displayName: 'Started After',
				name: 'started_after',
				type: 'dateTime',
				default: '',
				description: "Interpreted in the workflow's time zone",
				routing: { request: { qs: { started_after: '={{ DateTime.fromISO(String($value)).toISO() }}' } } },
			},
			{
				displayName: 'Started Before',
				name: 'started_before',
				type: 'dateTime',
				default: '',
				description: "Interpreted in the workflow's time zone",
				routing: { request: { qs: { started_before: '={{ DateTime.fromISO(String($value)).toISO() }}' } } },
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'multiOptions',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Canceled', value: 'canceled' },
					{ name: 'Incomplete', value: 'incomplete' },
					{ name: 'Incomplete Expired', value: 'incomplete_expired' },
					{ name: 'Past Due', value: 'past_due' },
					{ name: 'Paused', value: 'paused' },
					{ name: 'Trialing', value: 'trialing' },
					{ name: 'Unpaid', value: 'unpaid' },
				],
				default: [],
				routing: { request: { qs: { status: '={{$value}}' } } },
			},
			{
				displayName: 'Timezone',
				name: 'timezone',
				type: 'string',
				default: '',
				placeholder: 'Europe/Paris',
				description: 'IANA time zone used to render dates in the CSV (defaults to UTC)',
				routing: { request: { qs: { timezone: '={{$value}}' } } },
			},
		],
	},
];
