import type { INodeProperties } from 'n8n-workflow';
import { countryOptions, paginationProperties } from '../../Polar/shared/descriptions';
import { portalRouting } from '../shared/errorHandling';

const resource = ['order'];
const showGetAll = { resource, operation: ['getAll'] };
const byId = '=/customer-portal/orders/{{$parameter["orderId"]}}';

export const orderDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource } },
		options: [
			{
				name: 'Confirm Retry Payment',
				value: 'confirmRetryPayment',
				action: 'Confirm a retry payment',
				description: 'Retry paying a failed order with a Stripe confirmation token or a saved payment method',
				routing: portalRouting('POST', `${byId}/confirm-payment`),
			},
			{
				name: 'Generate Invoice',
				value: 'generateInvoice',
				action: 'Generate an order invoice',
				description: 'Trigger generation of the invoice for a paid order',
				routing: portalRouting('POST', `${byId}/invoice`),
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get an order',
				description: "Get one of the customer's orders",
				routing: portalRouting('GET', byId),
			},
			{
				name: 'Get Invoice',
				value: 'getInvoice',
				action: 'Get an order invoice',
				description: 'Get the URL of a generated invoice',
				routing: portalRouting('GET', `${byId}/invoice`),
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many orders',
				description: "List the customer's orders",
				routing: portalRouting('GET', '=/customer-portal/orders/'),
			},
			{
				name: 'Get Payment Status',
				value: 'getPaymentStatus',
				action: 'Get an order payment status',
				description: 'Get the status of the latest payment attempt for an order',
				routing: portalRouting('GET', `${byId}/payment-status`),
			},
			{
				name: 'Get Receipt',
				value: 'getReceipt',
				action: 'Get an order receipt',
				description: 'Get the receipt URL for a paid order',
				routing: portalRouting('GET', `${byId}/receipt`),
			},
			{
				name: 'Update',
				value: 'update',
				action: 'Update an order',
				description: 'Update the billing name and address shown on the invoice',
				routing: portalRouting('PATCH', byId),
			},
		],
		default: 'getAll',
	},
	{
		displayName: 'Order ID',
		name: 'orderId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource,
				operation: [
					'confirmRetryPayment',
					'generateInvoice',
					'get',
					'getInvoice',
					'getPaymentStatus',
					'getReceipt',
					'update',
				],
			},
		},
	},
	...paginationProperties(showGetAll),
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: showGetAll },
		options: [
			{
				displayName: 'Billing Type',
				name: 'product_billing_type',
				type: 'multiOptions',
				options: [
					{ name: 'One Time', value: 'one_time' },
					{ name: 'Recurring', value: 'recurring' },
				],
				default: [],
				routing: { request: { qs: { product_billing_type: '={{$value}}' }, arrayFormat: 'repeat' } },
			},
			{
				displayName: 'Product ID',
				name: 'product_id',
				type: 'string',
				default: '',
				routing: { request: { qs: { product_id: '={{$value}}' } } },
			},
			{
				displayName: 'Query',
				name: 'query',
				type: 'string',
				default: '',
				description: 'Free-text search',
				routing: { request: { qs: { query: '={{$value}}' } } },
			},
			{
				displayName: 'Subscription ID',
				name: 'subscription_id',
				type: 'string',
				default: '',
				routing: { request: { qs: { subscription_id: '={{$value}}' } } },
			},
		],
	},
	{
		displayName: 'Payment Fields',
		name: 'paymentFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource, operation: ['confirmRetryPayment'] } },
		description: 'Provide either a Stripe confirmation token or a saved payment method ID',
		options: [
			{
				displayName: 'Confirmation Token ID',
				name: 'confirmation_token_id',
				type: 'string',
				typeOptions: { password: true },
				default: '',
				description: 'Stripe confirmation token ID for a new payment method',
				routing: { request: { body: { confirmation_token_id: '={{$value}}' } } },
			},
			{
				displayName: 'Payment Method ID',
				name: 'payment_method_id',
				type: 'string',
				default: '',
				description: 'ID of a payment method the customer already saved',
				routing: { request: { body: { payment_method_id: '={{$value}}' } } },
			},
		],
	},
	{
		displayName: 'Update Fields',
		name: 'updateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource, operation: ['update'] } },
		options: [
			{
				displayName: 'Billing Address City',
				name: 'billing_address_city',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'billing_address.city' } },
			},
			{
				displayName: 'Billing Address Country',
				name: 'billing_address_country',
				type: 'options',
				options: countryOptions,
				default: 'US',
				description: 'Required whenever any billing address field is set',
				routing: { send: { type: 'body', property: 'billing_address.country' } },
			},
			{
				displayName: 'Billing Address Line 1',
				name: 'billing_address_line1',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'billing_address.line1' } },
			},
			{
				displayName: 'Billing Address Line 2',
				name: 'billing_address_line2',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'billing_address.line2' } },
			},
			{
				displayName: 'Billing Address Postal Code',
				name: 'billing_address_postal_code',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'billing_address.postal_code' } },
			},
			{
				displayName: 'Billing Address State',
				name: 'billing_address_state',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'billing_address.state' } },
			},
			{
				displayName: 'Billing Name',
				name: 'billing_name',
				type: 'string',
				default: '',
				routing: { send: { type: 'body', property: 'billing_name' } },
			},
		],
	},
];
