import type { INodeProperties } from 'n8n-workflow';
import { paginationProperties } from '../../Polar/shared/descriptions';
import { portalRouting } from '../shared/errorHandling';

const resource = ['subscription'];
const showGetAll = { resource, operation: ['getAll'] };
const byId = '=/customer-portal/subscriptions/{{$parameter["subscriptionId"]}}';

export const subscriptionDescription: INodeProperties[] = [
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: { show: { resource } },
		options: [
			{
				name: 'Cancel',
				value: 'cancel',
				action: 'Cancel a subscription',
				description: "Cancel one of the customer's subscriptions",
				routing: portalRouting('DELETE', byId),
			},
			{
				name: 'Change Product',
				value: 'changeProduct',
				action: 'Change a subscription product',
				description: 'Switch the subscription to another product (upgrade or downgrade)',
				routing: portalRouting('PATCH', byId),
			},
			{
				name: 'Clear Pending Update',
				value: 'clearPendingUpdate',
				action: 'Clear a subscription pending update',
				description: 'Cancel a scheduled product or seat change before it takes effect',
				routing: portalRouting('PATCH', byId, { pending_update: null }),
			},
			{
				name: 'Get',
				value: 'get',
				action: 'Get a subscription',
				description: "Get one of the customer's subscriptions",
				routing: portalRouting('GET', byId),
			},
			{
				name: 'Get Many',
				value: 'getAll',
				action: 'Get many subscriptions',
				description: "List the customer's subscriptions",
				routing: portalRouting('GET', '=/customer-portal/subscriptions/'),
			},
			{
				name: 'Pause',
				value: 'pause',
				action: 'Pause a subscription',
				description: 'Pause the subscription now or at the end of the current period',
				routing: portalRouting('PATCH', byId),
			},
			{
				name: 'Resume',
				value: 'resume',
				action: 'Resume a subscription',
				description: 'Resume a paused subscription',
				routing: portalRouting('PATCH', byId, { resume: true }),
			},
			{
				name: 'Update Cancellation',
				value: 'updateCancellation',
				action: 'Update a subscription cancellation',
				description:
					'Schedule cancellation at the end of the current period (with a reason), or undo a scheduled cancellation',
				routing: portalRouting('PATCH', byId),
			},
			{
				name: 'Update Seats',
				value: 'updateSeats',
				action: 'Update subscription seats',
				description: 'Change the number of seats of a seat-based subscription',
				routing: portalRouting('PATCH', byId),
			},
			{
				name: 'Update Units',
				value: 'updateUnits',
				action: 'Update subscription units',
				description: 'Change the number of units of a unit-based subscription',
				routing: portalRouting('PATCH', byId),
			},
		],
		default: 'getAll',
	},
	{
		displayName: 'Subscription ID',
		name: 'subscriptionId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: {
				resource,
				operation: [
					'cancel',
					'changeProduct',
					'clearPendingUpdate',
					'get',
					'pause',
					'resume',
					'updateCancellation',
					'updateSeats',
					'updateUnits',
				],
			},
		},
	},
	...paginationProperties(showGetAll),
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Filter',
		default: {},
		displayOptions: { show: showGetAll },
		options: [
			{
				displayName: 'Active',
				name: 'active',
				type: 'boolean',
				default: true,
				description: 'Whether to only return active (true) or only inactive (false) subscriptions',
				routing: { request: { qs: { active: '={{$value}}' } } },
			},
			{
				displayName: 'Product ID',
				name: 'product_id',
				type: 'string',
				default: '',
				routing: { request: { qs: { product_id: '={{$value}}' } } },
			},
			{
				displayName: 'Query',
				name: 'query',
				type: 'string',
				default: '',
				description: 'Free-text search',
				routing: { request: { qs: { query: '={{$value}}' } } },
			},
		],
	},
	{
		displayName: 'Product ID',
		name: 'productId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: { show: { resource, operation: ['changeProduct'] } },
		description: 'ID of the product to switch to',
		routing: { send: { type: 'body', property: 'product_id' } },
	},
	{
		displayName: 'Seats',
		name: 'seats',
		type: 'number',
		default: 1,
		required: true,
		typeOptions: { minValue: 1 },
		displayOptions: { show: { resource, operation: ['updateSeats'] } },
		routing: { send: { type: 'body', property: 'seats' } },
	},
	{
		displayName: 'Units',
		name: 'units',
		type: 'number',
		default: 1,
		required: true,
		typeOptions: { minValue: 1 },
		displayOptions: { show: { resource, operation: ['updateUnits'] } },
		routing: { send: { type: 'body', property: 'units' } },
	},
	{
		displayName: 'Pause at Period End',
		name: 'pauseAtPeriodEnd',
		type: 'boolean',
		default: true,
		required: true,
		displayOptions: { show: { resource, operation: ['pause'] } },
		description: 'Whether to pause at the end of the current period instead of immediately',
		routing: { send: { type: 'body', property: 'pause_at_period_end' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'pauseFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource, operation: ['pause'] } },
		options: [
			{
				displayName: 'Resumes At',
				name: 'resumes_at',
				type: 'dateTime',
				default: '',
				description: 'When to resume the subscription automatically',
				routing: {
					request: { body: { resumes_at: '={{ DateTime.fromISO(String($value)).toISO() }}' } },
				},
			},
		],
	},
	{
		displayName: 'Cancel at Period End',
		name: 'cancelAtPeriodEnd',
		type: 'boolean',
		default: true,
		required: true,
		displayOptions: { show: { resource, operation: ['updateCancellation'] } },
		description:
			'Whether to cancel at the end of the current period (true) or undo a scheduled cancellation (false)',
		routing: { send: { type: 'body', property: 'cancel_at_period_end' } },
	},
	{
		displayName: 'Additional Fields',
		name: 'cancellationFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: { show: { resource, operation: ['updateCancellation'] } },
		options: [
			{
				displayName: 'Cancellation Comment',
				name: 'cancellation_comment',
				type: 'string',
				default: '',
				routing: { request: { body: { cancellation_comment: '={{$value}}' } } },
			},
			{
				displayName: 'Cancellation Reason',
				name: 'cancellation_reason',
				type: 'options',
				options: [
					{ name: 'Customer Service', value: 'customer_service' },
					{ name: 'Low Quality', value: 'low_quality' },
					{ name: 'Missing Features', value: 'missing_features' },
					{ name: 'Other', value: 'other' },
					{ name: 'Switched Service', value: 'switched_service' },
					{ name: 'Too Complex', value: 'too_complex' },
					{ name: 'Too Expensive', value: 'too_expensive' },
					{ name: 'Unused', value: 'unused' },
				],
				default: 'other',
				routing: { request: { body: { cancellation_reason: '={{$value}}' } } },
			},
		],
	},
];
